routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('lang/{locale}', 'LangController@lang');

Route::get('/admin', 'AdminController@admin')
    ->middleware('is_admin')
    ->name('admin');

Route::group(['middleware' => ['auth', 'is_admin']], function (){
    Route::resource('companies', 'CompaniesController');
    Route::resource('employee', 'EmployeeController');
});

resources/views/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Laravel 5.8</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    <a href="/companies" class="btn btn-success">Companies</a>
    <a href="/employee" class="btn btn-warning">Employee</a>
    @yield('content')
    @section('content')
    <div class="container">
      <div class="row justify-content-center">
          <div class="col-md-8">
              <div class="card">
                  <div class="card-body">
                  <p>{{ trans('sentence.welcome')}}</p>
                  </div>
              </div>
          </div>
      </div>
    </div>
    @endsection
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/create_companies.blade.php
@extends('layout_companies')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Company
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('companies.store') }}" enctype="multipart/form-data">
          <div class="form-group">
              @csrf
              <label for="name">Company Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>
          <div class="form-group">
              <label for="email">Email</label>
              <input type="text" class="form-control" name="email"/>
          </div>
          <div class="form-group">
              <label for="website">Website:</label>
              <input type="text" class="form-control" name="website"/>
          </div>
          <div class="form-group">
              <label for="logo">Logo:</label>
              <input type="file" class="form-control" name="logo">
          </div>
          <button type="submit" class="btn btn-primary">Create Company</button>
      </form>
  </div>
</div>
@endsection

resources/views/create_employee.blade.php
@extends('layout_companies')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Employer
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('employee.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">First Name</label>
              <input type="text" class="form-control" name="first_name"/>
          </div>
          <div class="form-group">
              <label for="last_name">Last name</label>
              <input type="text" class="form-control" name="last_name"/>
          </div>
          <div class="form-group">
              <label for="company">Company</label>
              <select class="form-control" name="company">
                @foreach($companies as $company)
                  <option value="{{$company->id}}">{{$company->name}}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
              <label for="email">Email</label>
              <input type="text" class="form-control" name="email"/>
          </div>
          <div class="form-group">
              <label for="phone">Phone</label>
              <input type="text" class="form-control" name="phone"/>
          </div>
          <button type="submit" class="btn btn-primary">Create Employer</button>
      </form>
  </div>
</div>
@endsection

resources/views/edit_companies.blade.php
@extends('layout_companies')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Book
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('companies.update', $company->id) }}" enctype="multipart/form-data">
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="name">Company Name:</label>
              <input type="text" class="form-control" name="name" value="{{$company->name}}"/>
          </div>
          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email" value="{{$company->email}}"/>
          </div>
          <div class="form-group">
              <label for="website">Website:</label>
              <input type="text" class="form-control" name="website" value="{{$company->website}}"/>
          </div>
          <div class="form-group">
              <label for="logo">Logo:</label>
              <input type="file" class="form-control" name="logo" value="{{storage_path('app/public/images')}}/{{$company->logo}}">
          </div>
          <button type="submit" class="btn btn-primary">Update Company</button>
      </form>
  </div>
</div>
@endsection

resources/views/edit_employee.blade.php
@extends('layout_companies')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Book
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('employee.update', $employee->id) }}">
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="first_name">First name</label>
              <input type="text" class="form-control" name="first_name" value="{{$employee->first_name}}"/>
          </div>
          <div class="form-group">
              <label for="last_name">Last name</label>
              <input type="text" class="form-control" name="last_name" value="{{$employee->last_name}}"/>
          </div>
          <div class="form-group">
              <label for="company">Company</label>
              <select class="form-control" name="company">
                @foreach($companies as $company)
                  <option value="{{$company->id}}" @if($employee->id == $company->id) selected="selected" @endif>{{$company->name}}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
              <label for="email">Email</label>
              <input type="text" class="form-control" name="email" value="{{$employee->email}}"/>
          </div>
          <div class="form-group">
              <label for="phone">Phone</label>
              <input type="text" class="form-control" name="phone" value="{{$employee->phone}}"/>
          </div>
          <button type="submit" class="btn btn-primary">Update Employer</button>
      </form>
  </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index_companies.blade.php
@extends('layout_companies')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif
  <a href="{{ route('companies.create') }}" class="btn btn-warning">Create Company</a>
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Company Name</td>
          <td>Email</td>
          <td>Website</td>
          <td>Logo</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($companies as $company)
        <tr>
            <td>{{$company->id}}</td>
            <td>{{$company->name}}</td>
            <td>{{$company->email}}</td>
            <td>{{$company->website}}</td>
            <td><img src="{{storage_path('app/public/images')}}/{{$company->logo}}" /></td>
            <td><a href="{{ route('companies.edit',$company->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('companies.destroy', $company->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
  {{ $companies->links() }}
<div>
@endsection

resources/views/index_employee.blade.php
@extends('layout_companies')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif
  <a href="{{ route('employee.create') }}" class="btn btn-warning">Create Employee</a>
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Company</td>
          <td>Email</td>
          <td>Phone</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($employee as $employer)
        <tr>
            <td>{{$employer->id}}</td>
            <td>{{$employer->first_name}} {{$employer->last_name}}</td>
            <td>
              @foreach($companies as $company)
                @if($employer->company == $company->id)
                 {{$company->name}}
                @endif
              @endforeach
            </td>
            <td>{{$employer->email}}</td>
            <td>{{$employer->phone}}</td>
            <td><a href="{{ route('employee.edit',$employer->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('employee.destroy', $employer->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
  {{ $employee->links() }}
<div>
@endsection

resources/views/layout_companies.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Laravel 5.8</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    <a href="{{url('/companies')}}" class="btn btn-success">Companies</a>
    <a href="{{url('/employee')}}" class="btn btn-warning">Employee</a>
    @yield('content')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/layout_employee.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Laravel 5.8</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    <a href="{{url('/companies')}}" class="btn btn-success">Companies</a>
    <a href="{{url('/employee')}}" class="btn btn-warning">Employee</a>
    @yield('content')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>